server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  # RabbitMQ相关配置
  rabbitmq:
    host: 192.168.64.3
    username: wanjia
    password: 123456
    virtual-host: /wanjia
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka