server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.64.3
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
wj:
  jwt:
    pubKeyPath: D:\project\tmp\rsa\rsa.pub # 公钥地址
    cookieName: WJ_TOKEN